$(document).ready(function(){    
    $("div.lugar1").hover(function(){
        $("#mapa2").attr("src","Images/1_LucianoCavalcante.png");    
    });
    $("div.lugar2").hover(function(){
        $("#mapa2").attr("src","Images/2_jardim.png");    
    });
    $("div.lugar3").hover(function(){
        $("#mapa2").attr("src","Images/3_tancredo.png");    
    });
    $("div.lugar4").hover(function(){
        $("#mapa2").attr("src","Images/4_tasso.png");    
    });
    $("div.lugar5").hover(function(){
        $("#mapa2").attr("src","Images/5_salinas.png");    
    });
    $("div.lugar6").hover(function(){
        $("#mapa2").attr("src","Images/6_boa_vista.png");    
    });
    $("div.lugar7").hover(function(){
        $("#mapa2").attr("src","Images/7_dias_macedo.png");    
    });
    $("div.lugar8").hover(function(){
        $("#mapa2").attr("src","Images/8_alto.png");    
    });
    $("div.lugar9").hover(function(){
        $("#mapa2").attr("src","Images/9_aerolandia.png");    
    });
    $("div.lugar10").hover(function(){
        $("#mapa2").attr("src","Images/10_joao.png");    
    });
    $("div.ultimo").hover(function(){
        $("#mapa2").attr("src","Images/11_guarapes.png");    
    });
    $("#localizacao").mouseout(function(){
        $("#mapa2").attr("src","Images/mapa2.png");
    });
});